###########  Deployment Server Port  ##############
server:
  port: 8081


###   MySql Databse Connnection   #######
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true